//! The art manifest's sheets must list exactly what the content pack has.
//!
//! `docs/art-manifest.json` is a batch input: an agent walks it and
//! generates one image per entry. The sheet entries name the cells to
//! draw, so a cell list that has drifted from the pack does not fail —
//! it quietly produces a set that is missing something, and nobody
//! notices until a room shows an item with no icon.
//!
//! That already happened once as prose: `ART.md` listed twelve items
//! against the pack's fifteen, so `hand_lamp`, `menders_kit` and
//! `porters_harness` — M6's whole kit-belongs-to-somebody-named idea —
//! would have been generated by nobody. This is the same shape as
//! `balance_doc.rs`: a doc that costs real work when it rots, so
//! something has to fail when it does.
//!
//! Ids are compared with their `item.` / `enemy.` prefix stripped,
//! because the manifest's cells are also file names and `ART.md`'s
//! naming rule is `room.mill` -> `art/rooms/mill.png`.

use crate::tests::content;

const MANIFEST: &str = include_str!("../../../../docs/art-manifest.json");

/// The manifest parses, and every asset carries the fields the batch
/// runner dereferences.
#[test]
fn the_manifest_is_well_formed() {
    let manifest = parse();
    let assets = manifest["assets"]
        .as_array()
        .expect("assets must be an array");
    assert!(!assets.is_empty(), "manifest lists no assets");

    for asset in assets {
        let id = asset["id"].as_str().expect("every asset needs an id");
        assert!(
            asset["out"].as_str().is_some(),
            "{id} has no output path, so a runner has nowhere to write it"
        );
        // A derived asset is cropped from another and has no prompt.
        if asset.get("derive").is_some() {
            continue;
        }
        assert!(
            asset["subject"].as_str().is_some_and(|s| !s.is_empty()),
            "{id} has no subject, so it would generate from the style block alone"
        );
    }
}

/// Every `{placeholder}` in a prompt resolves against `subject_canon`.
///
/// An unresolved one ships the literal text `{tower}` to an image
/// generator, which is the failure that loses the four-legged
/// silhouette in every asset at once.
#[test]
fn every_prompt_placeholder_resolves() {
    let manifest = parse();
    let canon = &manifest["subject_canon"];

    for asset in manifest["assets"].as_array().expect("assets") {
        let id = asset["id"].as_str().unwrap_or("<unnamed>");
        for field in ["subject", "composition"] {
            let Some(text) = asset[field].as_str() else {
                continue;
            };
            for name in placeholders(text) {
                assert!(
                    canon[&name].as_str().is_some(),
                    "{id}.{field} uses {{{name}}}, which subject_canon does not define"
                );
            }
        }
    }
}

#[test]
fn the_item_icon_sheet_lists_every_item_in_the_pack() {
    let expected: Vec<String> = content()
        .items
        .iter()
        .map(|item| strip_prefix(&item.id))
        .collect();

    assert_cells_match("item-icons", &expected);
}

#[test]
fn the_creature_sheet_lists_every_enemy_in_the_pack() {
    let expected: Vec<String> = content()
        .enemies
        .iter()
        .map(|enemy| strip_prefix(&enemy.id))
        .collect();

    assert_cells_match("creature-sheet", &expected);
}

/// The crew sheet draws the people a run can actually field: the first
/// `crew_cap` names, in the order `names.ron` lists them.
///
/// That order is load-bearing for replays (`add_crew` takes the next
/// name by index), so this also notices somebody alphabetising the file.
#[test]
fn the_crew_sheet_lists_the_crew_a_run_can_field() {
    let content = content();
    let cap = usize::from(content.balance.crew.crew_cap);
    assert!(
        content.crew_names.len() >= cap,
        "names.ron has {} names against a crew_cap of {cap}, so a full tower would wrap",
        content.crew_names.len()
    );

    let expected: Vec<String> = content.crew_names.iter().take(cap).cloned().collect();
    assert_cells_match("crew-sheet", &expected);
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn parse() -> serde_json::Value {
    serde_json::from_str(MANIFEST).expect("docs/art-manifest.json must be valid JSON")
}

/// `item.bamboo` -> `bamboo`.
fn strip_prefix(id: &str) -> String {
    id.split_once('.').map_or(id, |(_, rest)| rest).to_string()
}

/// The `{name}` placeholders in a prompt fragment.
fn placeholders(text: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut rest = text;
    while let Some(open) = rest.find('{') {
        let after = &rest[open + 1..];
        let Some(close) = after.find('}') else {
            break;
        };
        let name = &after[..close];
        if !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            found.push(name.to_string());
        }
        rest = &after[close + 1..];
    }
    found
}

fn assert_cells_match(asset_id: &str, expected: &[String]) {
    let manifest = parse();
    let asset = manifest["assets"]
        .as_array()
        .expect("assets")
        .iter()
        .find(|asset| asset["id"].as_str() == Some(asset_id))
        .unwrap_or_else(|| panic!("docs/art-manifest.json has no asset {asset_id:?}"));

    let cells: Vec<String> = asset["sheet"]["cells"]
        .as_array()
        .unwrap_or_else(|| panic!("{asset_id} has no sheet.cells"))
        .iter()
        .map(|cell| {
            cell.as_str()
                .unwrap_or_else(|| panic!("{asset_id} has a non-string cell"))
                .to_string()
        })
        .collect();

    let missing: Vec<&String> = expected.iter().filter(|id| !cells.contains(id)).collect();
    let extra: Vec<&String> = cells.iter().filter(|id| !expected.contains(id)).collect();

    assert!(
        missing.is_empty() && extra.is_empty(),
        "{asset_id} has drifted from the content pack.\n  \
         the pack has, and the sheet would not generate: {missing:?}\n  \
         the sheet would generate, and the pack does not have: {extra:?}"
    );
}
